spring.application.name=JournalApp_SpringBoot_Project
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
#spring.mongodb.username="myjournaldbuse"
#spring.mongodb.password="mypassword"

# write logs to this file
logging.file.name=logs/journal-app.log

# log level
logging.level.root=INFO
logging.level.com.pratice=DEBUG

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yogeshnakade298@gmail.com
spring.mail.password=YOUR_ACTUAL_GMAIL_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# to add logs in the file need to add this dependency in pom.xml AND SET properties



