spring.application.name=JournalApp_SpringBoot_Project
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
#spring.mongodb.username="myjournaldbuse"
#spring.mongodb.password="mypassword"

spring.profiles.active=prod
